// File generated by FlutterFire CLI.
//
// PLACEHOLDER — this stub exists so the project compiles before the real
// `flutterfire configure` step has been run. Run:
//
//     flutterfire configure --project=<your-project-id> --platforms=ios,android
//
// to replace this file with the real generated options. The generated file
// will pull real API keys from Firebase and should NOT be edited by hand.
//
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_fHSaQ6X3EFSqkahtaWyVcPJdHgw4uyE',
    appId: '1:883331518653:ios:2850990fe8dc2bc39627d4',
    messagingSenderId: '883331518653',
    projectId: 'noenemies-app',
    storageBucket: 'noenemies-app.firebasestorage.app',
    iosBundleId: 'com.gymstreaklabs.noEnemies',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_3tZKLyKryRVdQaPDCv57x-yGBVfopuA',
    appId: '1:883331518653:android:a7a2373643b81c929627d4',
    messagingSenderId: '883331518653',
    projectId: 'noenemies-app',
    storageBucket: 'noenemies-app.firebasestorage.app',
  );

}